version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    env_file:
      - .env
  api:
    build:
      context: ./api
    env_file:
      - ./api/.env
    restart: always
    depends_on:
      - db
    ports:
      - 127.0.0.1:8000:8000
  client:
    build:
      context: ./client
    env_file:
      - ./client/.env
    restart: always
    ports:
      - 127.0.0.1:3000:3000

networks:
  default:
    name: reverse-proxy
    external: true
