version: "3"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "6543:5432"
    env_file:
      - .env
  api:
    build:
      context: ./api
    env_file:
      - ./api/.env
    restart: always
    depends_on:
      - db
    ports:
      - 8000:8000
  client:
    build:
      context: ./client
    env_file:
      - ./client/.env
    restart: always
    ports:
      - 3000:3000
